config/routes.rb
Rails.application.routes.draw do
  root 'user#index'
  get 'user/list', to: 'user#list', as: 'list_user'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :user, except: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable

  validates :password, length: { maximum: 10 }
  validate :password_special_character

  enum role: {user: 0, staff: 1, admin: 2}
  
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  private

  def password_special_character
    return if password.blank?

    unless password.match?(/[^a-zA-Z0-9]/)
      errors.add :password, "must include at least one special character"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index; end

  def list
    @users =User.all
  end

  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      @user.send_reset_password_instructions
      redirect_to list_user_path
    else
      flash[:danger] = "Could not create a user."
      redirect_to list_user_path
    end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update(update_params)
      redirect_to list_user_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "You have deleted the user."
    redirect_to list_user_path, status: :see_other
  end
  
  private

  def update_params
    params.require(:user).permit(:name, :role)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:name, :role])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <%= link_to 'Home', root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%if user_signed_in?%>
        <%= link_to 'Profile', edit_user_registration_path, class: 'nav-link' %>
        <%= button_to 'Log-out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <%if current_user.admin?%>
          <%= link_to 'Users', list_user_path , class: 'nav-link' %>
        <%end%>

      <%else%>
        <%= link_to 'Log-in', new_user_session_path, class: 'nav-link' %>
        <%= link_to 'Sign-up', new_user_registration_path, class: 'nav-link' %>
      <%end%>
      <div>
      </div>  
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoECommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/user/edit.html.erb
<%= form_with model: @user, url: user_path do |f| %>
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h1>Edit User</h1>
            <div class="mb-3">
              <%= f.label :name, class: 'form-label' %>
              <%= f.text_field :name, class: 'form-control', required: true %>
              <div class="invalid-feedback">
                Please provide a name.
              </div>
            </div>

            <div class="mb-3">
              <%= f.label :role, class: 'form-label' %>
              <%= f.select :role, User.roles.keys.map { |r| [r.humanize, r] }, {}, class: 'form-select', required: true %>
              <div class="invalid-feedback">
                Please select a role.
              </div>
            </div>

            <div>
              <%= f.submit 'Submit', class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/user/index.html.erb
<h1>E-Commere Store</h1>

<% if current_user %>
  <p>Hello <%= current_user.role%></p>
<%end%>

app/views/user/list.html.erb
<h1>All Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="ID">ID</th>
      <th scope="Name">Name</th>
      <th scope="Email">Email</th>
      <th scope="role">Role</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user, index| %>
      <tr>
        <td><%=index+1%></td>
        <td><%=user.name%></td>
        <td><%=user.email%></td>
        <td><%=user.role%></td>
        <td><%= link_to "Edit", edit_user_path(user), class: "btn btn-success"%></td>
        <td><%= button_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %></td>
      </tr>
    <%end%>
  </tbody>
</table>

<%= link_to "New User", new_user_path , class: 'btn btn-primary'%>

app/views/user/new.html.erb
<%= form_with model: @user, url: user_index_path, method: :post do |f| %>
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h1>Create User</h1>
            <div class="mb-3">
              <%= f.label :name, class: 'form-label' %>
              <%= f.text_field :name, class: 'form-control', required: true %>
              <div class="invalid-feedback">
                Please provide a name.
              </div>
            </div>

            <div class="mb-3">
              <%= f.label :email, class: 'form-label' %>
              <%= f.email_field :email, class: 'form-control', required: true %>
              <div class="invalid-feedback">
                Please provide an email.
              </div>
            </div>

            <div class="mb-3">
              <%= f.label :password, class: 'form-label' %>
              <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %>
              <%= f.password_field :password, class: 'form-control', autocomplete: "new-password", required: true %>
              <div class="invalid-feedback">
                Please provide a password.
              </div>
            </div>

            <div class="mb-3">
              <%= f.label :password_confirmation, class: 'form-label' %>
              <%= f.password_field :password_confirmation, class: 'form-control', autocomplete: "new-password", required: true %>
              <div class="invalid-feedback">
                Please confirm your password.
              </div>
            </div>

            <div class="mb-3">
              <%= f.label :role, class: 'form-label' %>
              <%= f.select :role, User.roles.keys.map { |r| [r.humanize, r] }, {}, class: 'form-select', required: true %>
              <div class="invalid-feedback">
                Please select a role.
              </div>
            </div>

            <div>
              <%= f.submit 'Submit', class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>